### ISSUE TITLE
GoAPI Identifiers has Category information

### ISSUE THREAD

**Issue by dgallegos** [curt-labs/GoAPI#94]
http://goapi.curtmfg.com/part/identifiers?key=9300f7bc-2ca6-11e4-8758-42010af0fd79&brandID=1

The very last line of this has a string that looks like category information. For sure it's not a part identifier.

**Comment by awilsonCurt** [comment]
@dgallegos Looks like the issue here is bad data. There's a product that has "Class 2 Trailer Hitch with Ball Mount" as it's part number
![screenshot from 2017-02-21 13 08 52](https://cloud.githubusercontent.com/assets/25590753/23180413/fad91f9a-f836-11e6-87de-b2462c074666.png)

Been in there for almost a year looks like. Should it just be deleted?


Edit: Part looks good in the MySQL DB, listed with the part number of 121431, and "Class 2 Trailer Hitch with Ball Mount" is in the shortDesc.

**Comment by awilsonCurt** [comment]
@1brandeja5 Hey Jesse, do you know anything about this part? Seems to be good in MySQL, but a little off in mongo.

![screenshot from 2017-02-22 08 25 45](https://cloud.githubusercontent.com/assets/25590753/23215708/f62cd174-f8d8-11e6-8463-89b5b19c0035.png)

**Comment by dgallegos** [comment]
@1brandeja5 no need to look at this. I thought it was bad in MySQL. We'll take a look at this on our end.

**Comment by dgallegos** [comment]
@etimme  do you know if this part is in product desk too, or if it's just in our databases and we can delete it?

**Comment by dgallegos** [comment]
@etimme nevermind, this is a bug on our end and we'll just delete it.

**Comment by dgallegos** [comment]
@awilsonCurt can you delete the MySQL and MongoDB entry.

**Comment by awilsonCurt** [comment]
The part was re-indexed, and now has the correct data, and the old entry was deleted and does not show up anymore in the API

@dgallegos
